[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "command-utils"
version = "0.3.0"
description = "command line utilties"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [
    { name = "Qian" },
    { email = "gokinjolno112358@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[project.urls]
repository = "https://github.com/i1123581321/command_utils"

[project.scripts]
split-video = "ffmpeg_utils.split_video:main"
flac-to-mp3 = "ffmpeg_utils.flac_to_mp3:main"
split-text = "text_utils.split_text:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 80